require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WeeklyUpdatesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # WeeklyUpdate. As you add validations to WeeklyUpdate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeeklyUpdatesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all weekly_updates as @weekly_updates" do
      weekly_update = WeeklyUpdate.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:weekly_updates)).to eq([weekly_update])
    end
  end

  describe "GET show" do
    it "assigns the requested weekly_update as @weekly_update" do
      weekly_update = WeeklyUpdate.create! valid_attributes
      get :show, {:id => weekly_update.to_param}, valid_session
      expect(assigns(:weekly_update)).to eq(weekly_update)
    end
  end

  describe "GET new" do
    it "assigns a new weekly_update as @weekly_update" do
      get :new, {}, valid_session
      expect(assigns(:weekly_update)).to be_a_new(WeeklyUpdate)
    end
  end

  describe "GET edit" do
    it "assigns the requested weekly_update as @weekly_update" do
      weekly_update = WeeklyUpdate.create! valid_attributes
      get :edit, {:id => weekly_update.to_param}, valid_session
      expect(assigns(:weekly_update)).to eq(weekly_update)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WeeklyUpdate" do
        expect {
          post :create, {:weekly_update => valid_attributes}, valid_session
        }.to change(WeeklyUpdate, :count).by(1)
      end

      it "assigns a newly created weekly_update as @weekly_update" do
        post :create, {:weekly_update => valid_attributes}, valid_session
        expect(assigns(:weekly_update)).to be_a(WeeklyUpdate)
        expect(assigns(:weekly_update)).to be_persisted
      end

      it "redirects to the created weekly_update" do
        post :create, {:weekly_update => valid_attributes}, valid_session
        expect(response).to redirect_to(WeeklyUpdate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weekly_update as @weekly_update" do
        post :create, {:weekly_update => invalid_attributes}, valid_session
        expect(assigns(:weekly_update)).to be_a_new(WeeklyUpdate)
      end

      it "re-renders the 'new' template" do
        post :create, {:weekly_update => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested weekly_update" do
        weekly_update = WeeklyUpdate.create! valid_attributes
        put :update, {:id => weekly_update.to_param, :weekly_update => new_attributes}, valid_session
        weekly_update.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested weekly_update as @weekly_update" do
        weekly_update = WeeklyUpdate.create! valid_attributes
        put :update, {:id => weekly_update.to_param, :weekly_update => valid_attributes}, valid_session
        expect(assigns(:weekly_update)).to eq(weekly_update)
      end

      it "redirects to the weekly_update" do
        weekly_update = WeeklyUpdate.create! valid_attributes
        put :update, {:id => weekly_update.to_param, :weekly_update => valid_attributes}, valid_session
        expect(response).to redirect_to(weekly_update)
      end
    end

    describe "with invalid params" do
      it "assigns the weekly_update as @weekly_update" do
        weekly_update = WeeklyUpdate.create! valid_attributes
        put :update, {:id => weekly_update.to_param, :weekly_update => invalid_attributes}, valid_session
        expect(assigns(:weekly_update)).to eq(weekly_update)
      end

      it "re-renders the 'edit' template" do
        weekly_update = WeeklyUpdate.create! valid_attributes
        put :update, {:id => weekly_update.to_param, :weekly_update => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weekly_update" do
      weekly_update = WeeklyUpdate.create! valid_attributes
      expect {
        delete :destroy, {:id => weekly_update.to_param}, valid_session
      }.to change(WeeklyUpdate, :count).by(-1)
    end

    it "redirects to the weekly_updates list" do
      weekly_update = WeeklyUpdate.create! valid_attributes
      delete :destroy, {:id => weekly_update.to_param}, valid_session
      expect(response).to redirect_to(weekly_updates_url)
    end
  end

end
